Repository cryptonative-ch/aqua-interface, pull requests merged in 2021-02, with the labels that each got.

#63 /simulation to /demo and some more improvments
  src/components/ErrorMessage/index.tsx
  src/components/Link/index.tsx
  src/router/index.tsx
Labels: enhancement

#74 Fix PlaceBidForm logic
  public/locales/en/translation.json
  src/views/Auction/components/PlaceBidForm.tsx
  src/views/Auction/index.tsx
  src/views/Simulation/index.tsx
Labels: bug

#78 Bidinfo
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  package.json
  public/locales/en/translation.json
  src/App.tsx
  src/components/Button/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/style.tsx
  src/contexts/index.tsx
  src/data/auction.ts
  src/hooks/useGenericModal.tsx
  src/hooks/useModal.tsx
  src/mesa/price.ts
  src/router/index.tsx
  src/views/Auction/components/BidList.tsx
  src/views/Auction/components/PlaceBidForm.tsx
  src/views/Auction/index.tsx
  src/views/Auctions/index.tsx
  src/views/Simulation/index.tsx
Labels: bug, enhancement
