Repository cryptonative-ch/aqua-interface, pull requests merged in 2021-08, with the labels that each got.

#374 Feature/handle sold out sales
  src/aqua/sale.ts
  src/views/Sale/components/SelfBidList/index.tsx
  src/views/Sales/index.tsx
Labels: enhancement

#380 Fixing max for when remaining tokens less than maxAllocation
  src/views/Sale/components/PurchaseTokensForm/index.tsx
Labels: bug

#387 fix: app crash on token claim
  src/hooks/useTokenClaim.ts
  src/redux/claims/index.ts
  src/views/Token/components/SuccessfulClaim/index.tsx
  src/views/Token/components/TokenClaim/index.tsx
Labels: bug, critical

#388 fix: first purchase error
  src/hooks/useBids.ts
  src/hooks/useChain.ts
  src/redux/bids/index.ts
  src/views/Sale/FairSale.tsx
Labels: bug, critical

#393 Chore/quick cleanup
  src/hooks/useBids.ts
  src/hooks/useFixedPriceSaleCommitmentsByBuyerId.ts
  src/hooks/useFixedPriceSaleCommitmentsQuery.ts
  src/hooks/useReadBidEventFromBlockchain.ts
  src/hooks/useTokenClaim.ts
  src/redux/bids/index.test.ts
  src/redux/bids/index.ts
  src/subgraph/SaleBids/index.ts
  src/subgraph/__generated__/GetAllBidsBySaleId.ts
  src/subgraph/__generated__/GetAllSales.ts
  src/subgraph/__generated__/GetAquaFactory.ts
  src/subgraph/__generated__/GetFixedPriceSaleCommitmentsByUser.ts
  src/subgraph/__generated__/GetSingleSale.ts
  src/subgraph/__generated__/fairSaleResults.ts
  src/subgraph/__generated__/fixedPriceSaleCommitments.ts
  src/subgraph/__generated__/fixedPriceSaleResults.ts
  src/subgraph/__generated__/fixedPriceSaleUsers.ts
  src/subgraph/__generated__/globalTypes.ts
  src/subgraph/__generated__/tokenResults.ts
  src/subgraph/index.spec.ts
  src/subgraph/index.ts
  src/subgraph/queries.ts
  src/utils/Defaults/index.tsx
  src/utils/index.test.ts
  src/utils/index.ts
  src/views/Sale/FairSale.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/BarChart.tsx
  src/views/Sale/components/HeaderControl/index.spec.tsx
  src/views/Sale/components/HeaderControl/index.tsx
  src/views/Sale/components/PlaceBidForm/index.spec.tsx
  src/views/Sale/components/PurchaseTokensForm/index.tsx
  src/views/Sale/components/SaleHeader/index.spec.tsx
  src/views/Sale/components/SelfBidList/index.spec.tsx
  src/views/Sale/components/SelfBidList/index.tsx
  src/views/Sale/components/TokenFooter/index.spec.tsx
  src/views/Sales/components/SaleAmount/index.spec.tsx
  src/views/Sales/components/SaleAmount/index.tsx
  src/views/Sales/components/SaleClock/index.spec.tsx
  src/views/Sales/components/SaleFinalPrice/index.spec.tsx
  src/views/Sales/components/SaleFinalPrice/index.tsx
  src/views/Sales/components/SaleSummaryCard/index.spec.tsx
  src/views/Sales/index.tsx
  src/views/Token/components/SuccessfulClaim/index.tsx
Labels: enhancement

#397 fix: redux bids error
  public/locales/en/translation.json
  src/hooks/useBids.ts
  src/hooks/useReadBidEventFromBlockchain.ts
  src/redux/bids/index.test.ts
  src/redux/bids/index.ts
  src/utils/index.ts
  src/views/Sales/index.tsx
  src/views/Token/components/TokenClaim/index.tsx
  src/views/Token/index.tsx
Labels: bug, critical

#406 Adding more accuracy to progress bar for clarity
  src/views/Sale/components/HeaderControl/index.tsx
Labels: bug

#407 removing unused variable for build
  src/hooks/useReadBidEventFromBlockchain.ts
Labels: bug

#412 Bug/subgraph claim
  package.json
  public/locales/en/translation.json
  src/components/Table/index.tsx
  src/hooks/useFixedPriceSaleCommitmentsByBuyerId.ts
  src/hooks/useTokenClaim.ts
  src/interfaces/Sale.ts
  src/subgraph/__generated__/GetAllSales.ts
  src/subgraph/__generated__/GetFixedPriceSaleCommitmentsByUser.ts
  src/subgraph/__generated__/GetSingleSale.ts
  src/subgraph/__generated__/fairSaleResults.ts
  src/subgraph/__generated__/fixedPriceSaleCommitments.ts
  src/subgraph/__generated__/fixedPriceSaleResults.ts
  src/subgraph/__generated__/fixedPriceSaleUsers.ts
  src/subgraph/__generated__/globalTypes.ts
  src/subgraph/__generated__/launchedTemplateResults.ts
  src/utils/index.ts
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/HeaderClaim/index.tsx
  src/views/Sale/components/SelfBidList/index.tsx
  src/views/Token/components/TokenClaim/index.tsx
Labels: bug

#416 fix: inconsistent sales loading
  src/views/Sales/index.tsx
Labels: bug

#423 Added modal confirmation for closing sale
  public/locales/en/translation.json
  src/hooks/useTokenClaim.ts
  src/views/Sale/components/HeaderClaim/index.tsx
  src/views/Sale/components/HeaderControl/index.spec.tsx
  src/views/Sale/components/HeaderControl/index.tsx
Labels: enhancement

#421 fix: FixedPriceSaleView not updating on sale change
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/SaleHeader/index.tsx
Labels: bug

#417 fix: RpcError on reject
  src/hooks/useTokenClaim.ts
  src/interfaces/Error.ts
Labels: bug

#436 Purchase and claim buttons added for mobile
  src/components/Header/index.tsx
  src/components/Header/style.tsx
  src/components/MobileFooter/index.tsx
  src/components/MobileFooter/style.tsx
  src/views/Sale/FairSale.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/HeaderClaim/ClaimButton.tsx
  src/views/Sale/components/HeaderClaim/index.tsx
  src/views/Static/index.tsx
Labels: enhancement

#446 Feature/fair sale bids and chart
  graphql-schema.json
  src/constants/index.ts
  src/hooks/useBids.ts
  src/hooks/useNewBidEventFromChain.ts
  src/hooks/useReadBidEventFromBlockchain.ts
  src/redux/commitments/index.test.ts
  src/redux/commitments/index.ts
  src/redux/store.ts
  src/subgraph/__generated__/GetAllBidsBySaleId.ts
  src/subgraph/__generated__/GetAllSales.ts
  src/subgraph/__generated__/GetAquaFactory.ts
  src/subgraph/__generated__/GetFixedPriceSaleCommitmentsByUser.ts
  src/subgraph/__generated__/GetSingleSale.ts
  src/subgraph/__generated__/fairSaleResults.ts
  src/subgraph/__generated__/fixedPriceSaleCommitments.ts
  src/subgraph/__generated__/fixedPriceSaleResults.ts
  src/subgraph/__generated__/fixedPriceSaleUsers.ts
  src/subgraph/__generated__/globalTypes.ts
  src/subgraph/__generated__/launchedTemplateResults.ts
  src/subgraph/__generated__/tokenResults.ts
  src/subgraph/queries.ts
  src/views/Sale/FairSale.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/BarChart.tsx
  src/views/Sale/components/PurchaseTokensForm/index.tsx
Labels: enhancement
