Repository cryptonative-ch/aqua-interface, pull requests merged in 2021-06, with the labels that each got.

#196 feature/network-warning
  public/locales/en/translation.json
  src/components/Banner/index.tsx
  src/components/Banner/style.tsx
  src/components/Header/index.tsx
  src/components/Header/style.tsx
  src/constants/index.ts
  src/redux/network/index.test.ts
  src/redux/network/index.ts
  src/redux/store.ts
  src/views/Sale/components/PurchaseTokensForm/index.tsx
  src/views/Sales/index.tsx
Labels: enhancement

#192 Feature/sale view/token claim cards
  package.json
  public/locales/en/translation.json
  src/App.tsx
  src/assets/svg/External-Link.svg
  src/blockchain/index.ts
  src/components/Button/index.tsx
  src/components/Card/index.tsx
  src/components/CardText/index.tsx
  src/components/Grid/index.ts
  src/components/Icon/index.tsx
  src/components/Spinner/index.tsx
  src/components/Title/index.tsx
  src/components/TokenIconFigure/index.ts
  src/interfaces/Sale.ts
  src/router/index.tsx
  src/views/Sale/components/Timer/index.spec.tsx
  src/views/Sales/components/SaleSummaryCard/index.tsx
  src/views/Sales/index.tsx
  src/views/Token/components/FailedClaim/index.tsx
  src/views/Token/components/SuccessfulClaim/index.tsx
  src/views/Token/components/TokenClaim/index.tsx
  src/views/Token/components/VerifyClaim/index.tsx
  src/views/Token/index.tsx
Labels: enhancement

#202 feature/updateGithubActionForDev adding dev branch and fixing build c…
  .github/workflows/github_action.yml
Labels: enhancement

#217 feature/approve-buy-button linked button component and fixed updating approval
  src/components/ErrorMessage/index.tsx
  src/components/LinkedButtons/index.tsx
  src/components/LinkedButtons/style.tsx
  src/components/Spinner/index.tsx
  src/hooks/useTokenAllowance.ts
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/PurchaseTokensForm/index.tsx
  src/views/Sale/index.tsx
  src/views/Sales/index.tsx
  src/views/Token/index.tsx
Labels: enhancement

#219 fixing eslint issues
  .eslintrc.js
  src/views/Sale/FairSale.tsx
  src/views/Sale/components/PlaceBidForm/index.tsx
  src/views/Sale/components/PurchaseTokensForm/index.tsx
  src/views/Sales/components/SaleSummaryCard/index.tsx
  src/views/Token/index.tsx
Labels: bug

#222 Bug/token view
  src/views/Token/components/FailedClaim/index.tsx
  src/views/Token/components/SuccessfulClaim/index.tsx
  src/views/Token/components/TokenClaim/index.tsx
  src/views/Token/index.tsx
Labels: bug

#238 fixed overlap issue
  src/components/Container/index.tsx
  src/components/Grid/index.ts
Labels: bug

#231 fixing css, decimal and max allocation issues
  src/views/Sale/components/PurchaseTokensForm/index.tsx
Labels: bug, enhancement

#242 Changed input to take xdai and calculate quantity
  src/components/LinkedButtons/index.tsx
  src/components/LinkedButtons/style.tsx
  src/views/Sale/components/PurchaseTokensForm/index.tsx
Labels: enhancement

#243 small ui changes
  public/locales/en/translation.json
  src/components/Header/index.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/BadgeCard/index.spec.tsx
  src/views/Sale/components/BadgeCard/index.tsx
  src/views/Sale/components/SaleHeader/index.spec.tsx
  src/views/Sale/components/SaleHeader/index.tsx
  src/views/Sale/components/TokenFooter/index.tsx
  src/views/Sales/components/SaleSummaryCard/index.spec.tsx
  src/views/Sales/components/SaleSummaryCard/index.tsx
Labels: bug, enhancement

#248 Bug/bidlist
  CONTRIBUTING.md
  __generated__/globalTypes.ts
  src/assets/index.ts
  src/blockchain/index.ts
  src/constants/index.ts
  src/hooks/useBids.ts
  src/hooks/useChain.ts
  src/interfaces/Sale.ts
  src/redux/bids/index.ts
  src/redux/sales/index.test.ts
  src/subgraph/SaleBids/index.ts
  src/subgraph/__generated__/GetAllSales.ts
  src/subgraph/__generated__/GetSingleSale.ts
  src/subgraph/__generated__/fixedPriceSaleResults.ts
  src/subgraph/attributes.ts
  src/views/Sale/FairSale.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/HeaderControl/index.tsx
  src/views/Sale/components/SelfBidList/index.tsx
Labels: bug, enhancement

#257 fixing footer issues and refreshing header bar issue
  src/App.tsx
  src/components/Grid/index.ts
  src/views/Sale/FairSale.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/index.tsx
  src/views/Sales/index.tsx
  src/views/Static/index.tsx
  src/views/Token/index.tsx
Labels: bug

#260 Bug/token claim button
  src/hooks/useBids.ts
  src/hooks/useChain.ts
  src/hooks/useTokenClaim.ts
  src/interfaces/Sale.ts
  src/views/Sale/FixedPrice.tsx
  src/views/Token/components/TokenClaim/index.tsx
Labels: bug, enhancement

#268 Bug/progress bar
  src/utils/Defaults/index.tsx
  src/views/Sale/FairSale.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/HeaderControl/index.spec.tsx
  src/views/Sale/components/HeaderControl/index.tsx
  src/views/Sale/components/SelfBidList/index.tsx
  src/views/Sales/components/SaleFinalPrice/index.tsx
Labels: bug, enhancement

#276 Bug/aggregate bids
  src/hooks/useBids.ts
  src/hooks/useTokenClaim.ts
  src/interfaces/Error.ts
  src/interfaces/Sale.ts
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/HeaderClaim/index.tsx
  src/views/Sale/components/HeaderControl/index.tsx
  src/views/Sales/components/SaleFinalPrice/index.tsx
Labels: bug, enhancement

#279 Bug/progress bar not visible
  src/hooks/useBids.ts
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/HeaderControl/index.spec.tsx
Labels: bug

#280 Toast notifications
  package.json
  public/locales/en/translation.json
  src/App.tsx
  src/components/Container/index.tsx
  src/components/Header/index.tsx
  src/hooks/useApprovalCallback.ts
  src/hooks/useChain.ts
  src/hooks/useSale.ts
  src/hooks/useSales.ts
  src/hooks/useTokenBalance.ts
  src/hooks/useTokenClaim.ts
  src/views/Sale/components/HeaderClaim/index.tsx
  src/views/Sale/components/PurchaseTokensForm/index.tsx
  src/views/Token/index.tsx
Labels: enhancement

#282 Feature/hide soft cap
  src/views/Sale/components/HeaderControl/index.tsx
  src/views/Sale/components/SelfBidList/index.tsx
Labels: enhancement

#293 refactor sales page and nav bar
  public/locales/en/translation.json
  src/components/SaleBadge/index.tsx
  src/redux/page/index.ts
  src/views/Sales/components/SaleNavBar/index.spec.tsx
  src/views/Sales/components/SaleNavBar/index.tsx
  src/views/Sales/index.tsx
Labels: enhancement

#301 Fixing accuracy issue
  src/hooks/useApprovalCallback.ts
  src/utils/Defaults/index.tsx
  src/views/Sale/components/PurchaseTokensForm/index.tsx
Labels: bug

#304 Added requested changes to wording of closed sale
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/HeaderControl/index.tsx
  src/views/Sale/components/HeaderItem/index.tsx
Labels: bug

#306 Changed all relative imports to absolute
  CONTRIBUTING.md
  src/App.tsx
  src/assets/index.ts
  src/components/BackButton/index.spec.tsx
  src/components/Banner/index.tsx
  src/components/Footer/index.spec.tsx
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/components/InfoTooltip/index.tsx
  src/components/LinkedButtons/index.tsx
  src/components/MobileFooter/index.tsx
  src/components/Modal/index.tsx
  src/components/Modal/style.tsx
  src/connectors/index.ts
  src/hooks/useApprovalCallback.ts
  src/hooks/useBids.ts
  src/hooks/useCookieModal.tsx
  src/hooks/useSale.ts
  src/hooks/useSales.ts
  src/hooks/useTokenAllowance.ts
  src/hooks/useTokenBalance.ts
  src/index.tsx
  src/mesa/sale.ts
  src/redux/bids/index.test.ts
  src/redux/bids/index.ts
  src/redux/network/index.test.ts
  src/redux/sales/index.test.ts
  src/redux/sales/index.ts
  src/redux/store.ts
  src/styles/Global.tsx
  src/styles/styled.d.ts
  src/subgraph/index.spec.ts
  src/subgraph/index.ts
  src/subgraph/mock/server.ts
  src/subgraph/queries.ts
  src/utils/Defaults/index.test.ts
  src/utils/timezone/index.ts
  src/views/Sale/FairSale.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/BadgeCard/index.spec.tsx
  src/views/Sale/components/HeaderControl/index.spec.tsx
  src/views/Sale/components/HeaderItem/index.spec.tsx
  src/views/Sale/components/PlaceBidForm/index.spec.tsx
  src/views/Sale/components/PlaceBidForm/index.tsx
  src/views/Sale/components/SaleHeader/index.spec.tsx
  src/views/Sale/components/SelfBidList/index.spec.tsx
  src/views/Sale/components/Timer/index.spec.tsx
  src/views/Sale/components/TokenFooter/index.spec.tsx
  src/views/Sale/index.tsx
  src/views/Sales/components/SaleAmount/index.spec.tsx
  src/views/Sales/components/SaleClock/index.spec.tsx
  src/views/Sales/components/SaleFinalPrice/index.spec.tsx
  src/views/Sales/components/SaleNavBar/index.spec.tsx
  src/views/Sales/components/SaleSummaryCard/index.spec.tsx
  src/views/Sales/components/SaleSummaryCard/index.tsx
  src/views/Sales/index.tsx
  src/views/Static/components/StaticContent/index.spec.tsx
  src/views/Static/components/StaticHeader/index.spec.tsx
  src/views/Static/index.tsx
  src/views/Token/index.tsx
Labels: enhancement

#288 Bug/withdraw
  src/components/Table/index.tsx
  src/components/Table/style.tsx
  src/hooks/useBids.ts
  src/hooks/useModal.tsx
  src/subgraph/SaleBids/index.ts
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/HeaderItem/index.tsx
  src/views/Sale/components/SelfBidList/index.spec.tsx
  src/views/Sale/components/SelfBidList/index.tsx
Labels: bug

#311 updated scroll bar
  package.json
  src/components/Table/index.tsx
  src/components/Table/style.tsx
Labels: enhancement

#312 Feature/eslint
  .eslintrc.js
  package.json
  src/components/Header/index.tsx
  src/components/Table/index.tsx
  src/hooks/useApprovalCallback.ts
  src/hooks/useChain.ts
  src/hooks/useTokenClaim.ts
  src/redux/bids/index.ts
  src/redux/sales/index.ts
  src/views/Sale/FairSale.tsx
  src/views/Sale/components/HeaderControl/index.tsx
  src/views/Sale/components/HeaderItem/index.tsx
  src/views/Sale/components/PurchaseTokensForm/index.tsx
  src/views/Sale/components/Timer/index.spec.tsx
Labels: enhancement

#313 Fixing bug with approval form
  src/components/LinkedButtons/index.tsx
  src/hooks/useApprovalCallback.ts
  src/views/Sale/components/PurchaseTokensForm/index.tsx
Labels: bug
