Repository cryptonative-ch/aqua-interface, pull requests merged in 2021-05, with the labels that each got.

#138 Feature/sale bar
  README.md
  src/interfaces/Auction.ts
  src/redux/bidData/index.test.ts
  src/redux/bidData/index.ts
  src/subgraph/AuctionBids/index.ts
  src/subgraph/Auctions/index.ts
  src/subgraph/index.spec.ts
  src/subgraph/index.ts
  src/subgraph/mock/index.ts
  src/views/Auction/FixedPrice.tsx
  src/views/Auction/components/HeaderControl/index.spec.tsx
  src/views/Auction/components/HeaderControl/index.tsx
  src/views/Auction/index.tsx
Labels: enhancement

#142 Bug/bidlist
  src/interfaces/Sale.ts
  src/subgraph/index.ts
  src/utils/Defaults/index.tsx
  src/views/Sale/components/HeaderControl/index.tsx
  src/views/Sale/components/SelfBidList/index.tsx
Labels: bug, enhancement

#148 added default image
  src/assets/svg/no_token_image.svg
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/SaleHeader/index.tsx
  src/views/Sales/components/SaleSummaryCard/index.tsx
  src/views/Sales/index.tsx
Labels: enhancement

#150 Feature/blockchainpolling
  src/blockchain/index.ts
  src/interfaces/Sale.ts
  src/mesa/sale.ts
  src/redux/BidData/index.ts
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/SaleHeader/index.tsx
  src/views/Sale/components/SelfBidList/index.tsx
Labels: bug, critical, enhancement

#157 Chore/dayjs
  src/assets/svg/no-token-image.svg
  src/assets/svg/wallet-connect.svg
  src/index.tsx
  src/utils/date.ts
  src/views/Sale/components/SaleHeader/index.tsx
  src/views/Sale/components/SelfBidList/index.tsx
  src/views/Sale/components/Timer/index.spec.tsx
  src/views/Sale/components/Timer/index.tsx
  src/views/Sales/components/SaleClock/index.spec.tsx
  src/views/Sales/components/SaleSummaryCard/index.spec.tsx
  src/views/Sales/components/SaleSummaryCard/index.tsx
Labels: bug

#163 Bug/localtimer
  package.json
  src/redux/sales/index.ts
  src/subgraph/mock/index.ts
  src/utils/date.ts
  src/utils/timezone/abbreviations.json
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/Approve/index.tsx
  src/views/Sale/components/PlaceBidForm/index.spec.tsx
  src/views/Sale/components/PlaceBidForm/index.tsx
  src/views/Sale/components/SaleHeader/index.spec.tsx
  src/views/Sale/components/SelfBidList/index.spec.tsx
  src/views/Sale/components/Timer/index.spec.tsx
  src/views/Sale/components/Timer/index.tsx
  src/views/Sale/index.tsx
  src/views/Sales/components/SaleClock/index.spec.tsx
  src/views/Sales/components/SaleClock/index.tsx
  src/views/Sales/components/SaleSummaryCard/index.spec.tsx
Labels: bug, critical

#166 created 404 page
  public/locales/en/translation.json
  src/blockchain/index.ts
  src/components/Title/index.tsx
  src/subgraph/index.ts
  src/views/NotFound/index.tsx
  src/views/Sale/FixedPrice.tsx
  src/views/Sale/components/PlaceBidForm/index.tsx
  src/views/Sale/index.tsx
  src/views/Sales/index.tsx
Labels: enhancement

#178 Add `PurchaseTokensForm` for `FixedPriceSale`
  src/views/Sale/components/PurchaseTokensForm/index.tsx
Labels: enhancement, epic

#179 Update `useTokenBalance`
  src/hooks/useTokenBalance.ts
Labels: bug
